version: '3'
services:
  prestashop:
    image: prestashop/prestashop:1.7
    ports:
      - 8080:80
    volumes:
      - ./prestashop:/var/www/html
    restart: always
    environment:
      - PS_INSTALL_AUTO=1
      - DB_SERVER=prestashop_db
      - DB_USER=root
      - DB_PASSWD=admin
  prestashop_db:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
